- cmd/main.go
- pkg/appendable/index_file.go
- pkg/appendable/index_file_test.go
- pkg/appendable/io.go
- pkg/appendable/io_test.go
Because we want to introduce other format types, first we should identify the JSONL specific logic and try to extend them. 
1) `DetermineDataHandler`: a method that checks the suffix of the filepath to identify the format. 
> *Is `strings.HasSuffix` enough? Or should there be more robust measures like content sniffing?*
<br />
2) Since `Serialize()` contains JSONL specific logic + `handleObject`, I wrote an interface `DataHandler` that implements `Synchronize`
> This is the header: `func (j JSONLHandler) Synchronize(f *IndexFile) error {`. 
> However, it would be nicer to have  `func (j JSONLHandler) Synchronize() error {` where
```go
type JSONLHandler struct{indexFile *IndexFile}
```
> But this would require a lot of refactoring, and I wanted to get your thoughts first. What I currently …
> Extend `Synchronize()`

- examples/client/index.html
The current query editor is a `<TextArea />` so the experience to update JSON is a bit limiting.
--
Note: I don't know your opinion on adding external dependencies, you may have purposely left it like so to solely focus on the Appendable. But I figured this would help with the experience.
I built a quick server to statically serve the `index.html` file with the index + dataset files and `appendable.min.js` library
[PROOF](https://github.com/friendlymatthew/localppendable)
> A JSON editor to build queries

- cmd/main.go
- examples/README.md
- package.json
Hey Kevin,
I saw in your `package.json` that you had the `http-server` dependency listed:
https://github.com/kevmo314/appendable/blob/ba36ad5524a48293173ba947f9de0970db317793/package.json#L23-L25
I assume this was for the [example readme](https://github.com/kevmo314/appendable/blob/main/examples/README.md). So I went in and filled out the remaining parts. 
This required me to write some scripts in `package.json`:
- `build-index`: builds the index file. (*this assumes you've properly loaded in `green_tripdata`*)
- `serve:example`: temporarily installs `http-server` and serves the content in `/client`
If you `cd` into `workspace/` and run the commands listed in the readme, you should be able to see a local version on http://192.168.1.157:8080/
--
On another note, I was shook when …
> Wrote scripts + added a time flag [-t]

- pkg/btree/bptree.go
- pkg/btree/bptree_test.go
Closes https://github.com/kevmo314/appendable/issues/16
> feat: add meta page abstraction

- pkg/appendable/csv_handler.go
- pkg/appendable/index_file_csv_test.go
- pkg/appendable/index_file_test.go
- pkg/appendable/io.go
Fixes #40 
> ```sh
> go run cmd/main.go -csv examples/workspace/green_tripdata_2023-01.csv
> 2024/01/18 12:39:38 Writing index file to examples/workspace/green_tripdata_2023-01.csv.index
> 2024/01/18 12:39:39 Done!
> ```
> `IndexFile` deep equality check

- pkg/btree/bptree.go
- pkg/btree/multi.go
- pkg/btree/node.go
- pkg/btree/pagefile.go
This also improves performance by quite a bit since it avoids linear scans.
> fix: use the node byte size to determine splits

- .github/workflows/example-client.yml
- examples/README.md
- examples/workspace/fetch_csv.py
- examples/workspace/fetch_jsonl.py
The github workflow calls `fetch_data.py` which retrieves the `jsonl` and `csv` formats for the data. To reduce overhead, I split the python scripts to `fetch_jsonl` and `fetch_csv`. 
This is simpler and nicer than creating some CLI that specifies which data to format in.
> Split python script

- examples/README.md
- examples/client/index.html
- examples/client/server.go
- package.json
- src/database.ts
- src/tests/database.test.ts
As I was debugging, I was running into a major blocker where after editing the Appendable library, I would rebuild and reserve the demo.
`http-server` must have some underlying caching time, but basically I would have to wait 6 minutes till I saw the following change. Instead of digging into modifying the configuration, I just created a `server.go`.
Now you can just run:
```sh
npm run example
```
> Switch server

- pkg/appendable/csv_handler.go
- pkg/appendable/index_file_csv_test.go
- pkg/appendable/index_file_test.go
- pkg/appendable/io.go
- pkg/protocol/protocol.go
This PR contains bug fixes and extra coverage to assert correctness between index files and CSV parsing
> Fix critical csv bugs

- pkg/appendable/csv_handler.go
- pkg/appendable/index_file_csv_test.go
- pkg/appendable/index_file_test.go
- pkg/protocol/protocol.go
Suppose you had a column containing numbers, when you append data, the data got cast as a string. This PR refactors the code and retains the correct type throughout read index file.
Also, number values should always be cast as `float64`. In some cases, it was cast as an integer.
> fix: Retain correct type after appending

- examples/client/index.html
> Add CSV table

- examples/client/editor.js
- examples/client/index.html
- examples/client/styles.css
- src/db/database.ts
- src/db/query-builder.ts
- src/db/query-validation.ts
- src/index-file.ts
Query chaining is more fluent and flexible in its query style. 
You can now write queries:
> ```typescript
> const query = await db
>   .where('trip_distance', '>=', 10)
>   .orderBy('trip_distance', 'ASC')
>   .select([
>       'VendorID',
>       'trip_distance',
>       'passenger_count',
>       'fare_amount',
>       'tip_amount',
>       'mta_tax'
>   ])
>   .get();
> ```
It's forkable, so you can write derived queries:
> ```typescript
> const query = await db.where("...");
> const derivedQuery = query.orderBy("...");
>```
This PR also introduces a JS editor to the demo. The editor can now toggle between JSON and JS. Depending on the editor, you can build a query in JSON form or through the chaining of clauses.
Since the demo's gotten a lot more features, I also separated the `.css` …
> feat: chain queries

- cmd/main.go
- pkg/appendable/index_file.go
- pkg/btree/bptree.go
- pkg/btree/multi.go
- pkg/btree/node.go
- pkg/handlers/csv.go
- pkg/handlers/csv_test.go
- pkg/handlers/equality_test.go
- pkg/handlers/jsonl.go
- pkg/handlers/jsonl_test.go
- pkg/mmap/mmap.go
- pkg/mmap/mmap_test.go
This switches the data file to memory mapped access so it doesn't require a copy.
> feat: memory map data file

- src/btree/bptree.ts
- src/btree/multi.ts
- src/btree/node.ts
- src/tests/bptree.test.ts
- src/tests/multi.test.ts
- src/tests/node.test.ts
- tsconfig.json
The new multi test case tests the `next()` function.
The `mockRangeResolver` makes the following assumptions:
1) fill the first 4096 bytes with zeros, since this is the garbage collector
2) for the subsequent `ith` page, it stores the `nextpointer` from the 12th byte position to 12 + 7th byte position. The next pointer is the offset of the start of the `i+1th` page.
> multi traverse test

- examples/client/index.html
Currently, the demo links to an invalid `.index` file. This PR fixes that
> Fix stale demo link

- examples/client/index.html
Closes #134 
Upon clicking the `execute` button, this PR disables the button until the query has been fetched. This fixes the misfires that happen when you spam the `execute` button.
> feat: prevent execute misfires

- src/db/database.ts
This removes fetches between yields unless a new page is fetched, further dropping the number of required requests.
> fix: use iterator to fetch memory pointer

- examples/client/index.html
- src/data-file.ts
- src/index-file/index-file.ts
- src/index.ts
- src/range-request.ts
Closes #158 
In our `init()`, this PR introduces a `Config` which contains the following:
```ts
export type Config = {
useMultipartByteRanges?: boolean
}
```
We drill this through and in `range-request.ts`, we add logic where if that flag is either undefined or false, we'll resolve each range individually, else we'll continue with multi-fetching. If we reach a `200` response when multi-fetching, we'll warn the user that this flag hasn't been set.
Tested via local
> feat: add useMultipart flag

- examples/client/index.html
Just a note: the initial page load fetches ~40 requests, because a good portion of those are from retrieving the index headers.
We reset the counters when we click on the execute button, as `execute` requeries the db.
So we go from ~40 requests to 13 requests every time we click execute. Just a note, since people might be a bit confused by that.
> feat: reset metrics to demo

- pkg/btree/node.go
- pkg/btree/node_test.go
Reduces the need to use `AppendUvarint`
Sorry for the delay, I wiped my mac clean :)
> feat: add size-variant

- .github/workflows/format.yml
Prettier fails even though running `npx prettier --check "**/*.{js,jsx,ts,tsx,css,scss,md,json}"`Maybe the CI needs a tighter scope
> ci: prettier

- pkg/appendable/appendable.go
- pkg/appendable/index_file.go
- pkg/handlers/csv.go
- pkg/handlers/jsonl.go
We were doing double work where in `handleJsonlObject`, we'd recompute the width value upon json token. Instead, we read the width directly from the metaslot
> feat: pass width upon index creation

- src/btree/traversal.ts
The `TraversalRecord`'s first element returns a leaf node. When there are no fitting records, we return an index, `i`, right outside the bounds of `leafPointers`. That is from `0..len(leafPointers)-1`, index is usually `len(leafPointers)`. 
This PR adds one extra catch statement within the `init()` that checks this assertion. If true, we return false.
> feat: handle no results yielded

- cmd/main.go
- pkg/appendable/index_file.go
- pkg/appendable/index_file_test.go
- pkg/btree/bptree.go
- pkg/handlers/csv_test.go
- pkg/handlers/jsonl.go
- pkg/handlers/jsonl_test.go
Closes #203 
This PR extends the CLI to specify a list of headers you wish to index.
Sample:
```sh
go run cmd/main.go -t -i  randdata.index -s wef -s yearn -jsonl randdata.jsonl  
```
We collect all strings with the `-s` tag to denote as "searchable". We drill this through, and before creating the pages and inserting the bptree, we check if a given `name` is searchable.
> feat: specify trigram

- pkg/metapage/multi.go
- pkg/metapage/multi_test.go
Similar methods like Next involve interacting with the buffer to read/write. Renamed this to be a getter fn
> feat: rename `NextSlot`

- pkg/metapage/multi.go
- pkg/metapage/multi_test.go
- pkg/metapage/slot.go
- pkg/metapage/slot_test.go
- pkg/pagefile/pagefile.go
`GetNextSlot()` doesn't take a `[]byte` since that wasn't used anywhere.
In addition, we use a `[][]bool` to keep track of the number of slots. Upon initializing the tree slot, we should fill the first element as true. In addition, the page index computation was off by 1.
> New slotting logic

- pkg/metapage/multi_test.go
- pkg/metapage/slot_test.go
Introduces three edge cases:
1) `NewMultiBPTree()` is a somewhat deceiving name. Under the hood, it creates a `LinkedMetaSlot`. We make sure we properly catch for this.
2) Fill 16 slots. After filling up 16 slots, we should make sure the page gets filled, our in-memory `[][]bool` slot checker behaves accordingly, and the # of pages is ideal. Also after adding, we collect the slots, iterate through, and make sure that given ps, ns where ps is the prev slot and ns is the new slot, ps + (slotSize) = ns
3) Fill 200 slots. Checks for the same asserts as the ones above.
> coverage: slots

- pkg/handlers/jsonl.go
When we handle a JSONL object line, we store a memory pointer of the following:
```go
mp := pointer.MemoryPointer{
Offset: data.Offset + uint64(fieldOffset),
Length: uint32(dec.InputOffset() - fieldOffset),
}
```
For the trigram case, we split a string into a bunch of trigrams that conveniently store the offset and the holistic length. We need to make sure when we insert the trigram into the btree, we update the memory pointer correctly.
The PR changes the faulty logic, which would iteratively increment the memory pointer's offset + length. However, this doesn't make sense as the offset for that iteration should be added to the offset from the original memory pointer.
> feat: store unique pointers for trigrams

- src/db/database.ts
- src/file/index-file.ts
Instead of seeking for one field type, `seek()` now does the following:
```
Given a fieldName (header) and a set of FieldTypes, returns a list of meta pages, mp, where mp.FieldName == header && mp.FieldType is contained in the set of FieldTypes.
```
> feat: change seek to accept a set of field types to search for

- src/db/database.ts
- src/search/tokenizer.ts
- src/tests/tokenizer.test.ts
This PR introduces the `NgramToken` type and updates the logic in Tokenizer.
Added a static `TextEncoder` to `Tokenizer()` which will encode each trigram's strings to an ArrayBuffer. It also contains the  ngram token's specific FieldType.Ngram type.
> feat: add ngram token type

- src/tests/index-file.test.ts
This assertion wasn't checked into the previous PR.
> coverage: add # entries assertion

- pkg/metapage/multi.go
- pkg/metapage/multi_test.go
Ref: https://github.com/kevmo314/appendable/pull/250#pullrequestreview-2009507034
This PR allocates 1 byte for the metadata length in `LinkedMetaPage`. The test case is refactored where `255` is the **greatest** possible value
> feat: change to one byte for LinkedMetaPage metadata length

- pkg/metapage/multi_test.go
The `metapage` test cases assert the correctness of the slot offsets for a given N entries.
> fix: assertions

- src/db/database.ts
- src/file/index-file.ts
- src/file/multi.ts
This PR contains two things:
1. The root pointer (`POINTER_BYTE`) is 8 bytes long. 
2. The first slot, that is `tree.metadata()` is the `FileMeta`. Before we traverse through pages, we need to peel the head.
> feat: rename pointers and update traversal logic

- pkg/handlers/jsonl.go
Closes #252 
This PR creates a edge case in `handleJsonlObject` for all `Ngrams`, where we pass the `MemoryPointer`'s `Length` as the entire `valueStr`.
**Note** - the reason why we do this is for the ranking heuristic
> feat: pass length

- pkg/hnsw/eucqueue_test.go
- pkg/hnsw/node.go
- pkg/hnsw/node_test.go
This PR fixes the floating point accuracy issue, as well as testing the Euclidian distance for `Vector`.
> node coverage

- .gitignore
CI broke because since the `search` dataset is derived from git tracing, not from a python script
> feat: fix ci

- pkg/hnsw/hnsw.go
- pkg/hnsw/hnsw_test.go
- pkg/hnsw/node.go
When you insert a vector, we need to establish bidirectional connection between our neighbors and the current node.
This PR contains Link. Please note, we also refactored the `Node`'s `friends` class to be a map of minqueues
> feat: link

- pkg/hnsw/hnsw.go
- pkg/hnsw/node.go
This PR adds two methods to `Node` to safely write and read the friends hashmap.
> Handle nil pointer bugs with `Node`

- pkg/hnsw/eucqueue.go
- pkg/hnsw/hnsw.go
- pkg/hnsw/hnsw_test.go
- pkg/hnsw/node.go
For `Insert` and `KNNSearch`, we need to traverse from the top layer .... qLayer (not included) and find the correct entry node. 
The correct entry node is the node who's max layer is greater than qLayer and is most closest to q amongst the entry node friends
> feat: find correct entry node

- pkg/hnsw/eucqueue.go
- pkg/hnsw/eucqueue_test.go
If a node `id` is already in the priority queue, when we `insert(id, new_dist)`, the priority queue should update that item with a new_dist.
> feat: upsert priority queue

- pkg/hnsw/eucqueue.go
- pkg/hnsw/eucqueue_test.go
Refactors #300 to remove the linear scan. Instead, we keep a `visited` map with the `Item` reference.
> revert linear scan

- pkg/hnsw/hnsw.go
- pkg/hnsw/hnsw_test.go
- pkg/hnsw/node.go
- pkg/hnsw/node_test.go
`NodeId` must be unique, and instead of manually incrementing the next node id upon insertion, we can atomically increment.
Also: removed fluff and extra parameters.
> quick feat: increment next-node-id

- pkg/hnsw/hnsw.go
- pkg/hnsw/hnsw_test.go
- pkg/hnsw/node.go
- pkg/hnsw/node_test.go
When we iterate through levels, specifically https://github.com/kevmo314/appendable/blob/main/pkg/hnsw/hnsw.go#L225
since level was a unsigned integer, we weren't iterating properly, as once level reached 0, it wraps around to the max value of `uint`.
> feat: iterate properly @ 3rd pass in `Insert`

- pkg/hnsw/hnsw.go
- pkg/hnsw/hnsw_test.go
We feed 32 vectors with the entry node as `[]float64{0, 0}`. As we iterate, the distances get further away from our q Vector: `[]float64{32, 32}`. 
We do a kNN search on `32, 32` and retrieve the 10 closest items
> feat: multiple insertions of vectors, retrieve 10 closest

- pkg/hnsw/eucqueue.go
- pkg/hnsw/eucqueue_test.go
- pkg/hnsw/hnsw_test.go
- pkg/hnsw/node.go
- pkg/hnsw/node_test.go
Vectors and everything vector-related now use `Float32`. Other variables are kept as `Float64` due to their dependence on external dependencies like `math`.
> switch to float32

- pkg/hnsw/eucqueue_test.go
- pkg/hnsw/hnsw.go
- pkg/hnsw/hnsw_test.go
- pkg/hnsw/node_test.go
Upon insertion or initialization, if the vector supplied does not have the same dimensionality specified as `vectorDim` in `Hnsw`, then it will panic.
> feat: guard vector dim

- pkg/hnsw/hnsw_test.go
These two commented test cases rely on randomness and the assertions use those random variables to check if the levels are non-decreasing. 
However, there are occurrences where this test case fails, which forces you to re-run a job.
> feat: comment out flaky test

- src/btree/node.ts
- src/btree/traversal.ts
Step 2 in #313
Note, when we call `BPTreeNode.fromMemoryPointer()`, it creates a new node with attributes passed in.
> feat: move child resolution to bptree node

- src/btree/node.ts
- src/btree/traversal.ts
> Cache n children

- pkg/hnsw/friends.go
- pkg/hnsw/friends_test.go
- pkg/hnsw/hnsw.go
- pkg/hnsw/hnsw_test.go
- pkg/hnsw/pq.go
- pkg/hnsw/pq_test.go
Upon insertion, we need to first find the closest entry node.
This means searching all layers from [qTopLayer + 1..TopLayer]
> feat: assert search layer

- pkg/hnsw/hnsw.go
- pkg/hnsw/hnsw_test.go
The last bits of logic in `Insert()` require Hnsw to update the entryPointID.
> Update HNSW scheme to keep track of `EntryPointId`

- pkg/hnsw/hnsw_test.go
Given a multi cluster graph, and a `q` = `(2, 2)`, we want to make sure the closest neighbors are pulled from both clusters and in correct order.
> Feat: cluster c search

- pkg/hnsw/hnsw_test.go
Suppose we wanted to search for the 10 nearest elements, but the entire graph itself has only 9 elements. This PR seeks to make sure it returns the `Min(num points in graph, # nearest elements wanted)`
> sequential search with upper bound param

- pkg/hnsw/heap.go
> faster update

- pkg/bptree/bptree.go
- pkg/bptree/bptree_test.go
- pkg/bptree/node.go
- pkg/bptree/node_test.go
- pkg/handlers/csv.go
- pkg/handlers/csv_test.go
- pkg/handlers/equality_test.go
- pkg/handlers/jsonl.go
- pkg/handlers/jsonl_test.go
- pkg/mocks/btree.go
- pkg/mocks/node.go
- pkg/pointer/referenced_value.go
This PR is simply code movement.
> Move `ReferencedValue` to sharable package

- pkg/pointer/referenced_value.go
`ReferenceId` is used for `BTree` operations
> feat: referenceId

- pkg/btree/node.go
A common trap when creating a `BTree` is to zero out `VectorDim`. However, a `VectorDim` of 0 proceeds to screw up the `Size` calculation.
> add guard to `Size`

- pkg/hnsw/heap.go
- pkg/hnsw/heap_test.go
When flushing the `Friends` to disk, we need a non-mutable way to traverse through the `DistHeap`. This PR contains the `Clone()` function which will perform a deep copy of the `DistHeap`.
> feat: clone

- pkg/hnsw/friends.go
Per the discord comments about flushing `Friends` to disk.
DMR till #368
> feat: check in max level for every friend id

- pkg/vectorpage/manager.go
- pkg/vectorpage/manager_test.go
This PR creates a `VectorPageManager` struct. When adding a node, the `VectorPageManager` is responsible for slotting `point id` in the btree and the respective closest friends in the bptree.
> feat: adjacency manager
