- pkg/btree/node.go
- pkg/btree/node_test.go
Leaf nodes should not be encoded with children
> fix: handle leaf encoding correctly

- pkg/btree/bptree.go
- pkg/btree/bptree_test.go
Closes https://github.com/kevmo314/appendable/issues/25
> fix: remove 12 byte header allocation

- .github/workflows/example-client.yml
Command is now 
```sh
go run cmd/main.go -jsonl examples/workspace/green_tripdata_2023-01.jsonl
```
> Update cmd for CI

- pkg/appendable/csv_handler.go
- pkg/appendable/index_file_csv_test.go
- pkg/appendable/index_file_test.go
- pkg/appendable/io.go
> More CSV tests

- README.md
small nit and linked demo's readme
> Readme nits

- examples/client/index.html
- pkg/appendable/csv_handler.go
- src/database.ts
- src/index.ts
- src/tests/database.test.ts
This contains the format enum specification and some print statements.
I plan on merging this right now so that I can compare side by side with my local environment and prod. I've been pulling my hair just reverting changes back and forth so this will be nicer for quality of life
> Specify Format type

- pkg/btree/bptree.go
This was left in here for some debugging.
> chore: remove debugging block

- pkg/btree/bptree.go
- pkg/btree/node.go
- pkg/btree/node_test.go
Closes Remove `Offset` for pointers #91
> feat: use uint64 for internal pointers

- pkg/btree/bptree.go
Drops the green tripdata processing from ~1m8s to ~52s.
> feat: speed up traverse search with binary search

- pkg/btree/bptree.go
- pkg/btree/bptree_test.go
> feat: add iterator to b+ tree

- pkg/btree/bptree.go
- pkg/btree/bptree_test.go
Maybe this is easier to understand too...
> fix: use recursive incr implementation

- .github/workflows/benchmark.yml
- pkg/handlers/jsonl.go
Closes Add GitHub profiling #92
> feat: add continuous benchmarking

- .gitignore
- examples/client/index.html
- src/db/database.ts
- src/db/query-validation.ts
- src/index.ts
- src/tests/query-builder.test.ts
- src/tests/query-validation.test.ts
Validates the query before firing
> feat: query validation

- examples/client/index.html
- src/btree/bptree.ts
- src/btree/multi.ts
- src/btree/node.ts
- src/btree/pagefile.ts
- src/data-file.ts
- src/index-file/index-file.ts
- src/index.ts
- src/range-request.ts
- src/resolver.ts
- src/tests/bptree.test.ts
- src/tests/index-file.test.ts
- src/tests/multi.test.ts
- src/tests/node.test.ts
> feat: accept multiple ranges

- examples/client/index.html
The demo is working as normal:
> Fix undefined execute button

- src/data-file.ts
- src/index-file/index-file.ts
> fix fallback range resolver request

- src/range-request.ts
> handle 416

- examples/chat/DESIGN.md
- examples/chat/package-lock.json
- examples/chat/package.json
- examples/chat/src/App.tsx
- examples/chat/src/chat/channel.tsx
- examples/chat/src/chat/textbar.tsx
- examples/chat/src/header.tsx
- examples/chat/src/user.tsx
- built chat components
- set and tested cookie functionality for username (auto-generated)
if you're curious, run `npm run dev` in `/chat`
> feat: chat design

- pkg/btree/bptree.go
- pkg/btree/node.go
- pkg/btree/node_test.go
- pkg/mocks/main.go
Side effect occurs in the `node_test.go`. Moved this to the `mocks` package
> feat: remove side effect

- examples/visualizer/main.go
- pkg/appendable/index_file.go
- pkg/handlers/equality_test.go
- pkg/metapage/slot.go
- pkg/metapage/slot_test.go
- pkg/mocks/metadata.go
#191 is a proof of concept with a lot of rushed code, this way we can peel back the logic individually
> feat: split out paging

- src/btree/bptree.ts
- src/btree/node.ts
- src/btree/traversal.ts
- src/db/database.ts
- src/db/query-builder.ts
- src/file/data-file.ts
- src/file/pagefile.ts
fixed nits + warnings in the ts version
> feat: fix warnings

- pkg/btree/bptree.go
- pkg/btree/bptree_test.go
- src/btree/traversal.ts
- src/tests/bptree.test.ts
https://github.com/kevmo314/appendable/pull/202/files for golang
> fix: starting beyond tree causes error

- pkg/metapage/multi.go
> feat: change metadata size

- pkg/trigram/trigram.go
- pkg/trigram/trigram_test.go
This PR casts all trigrams to lower cases before inserting to bptree.
Btw did you feel that earthquake?
> feat: trigrams to lowercase

- examples/README.md
- package.json
Some scripts in package.json was rotting. This PR removes them
> chore: remove script rot

- .gitignore
- examples/search/index.html
- examples/search/server.go
- package.json
- src/file/index-file.ts
Just the scaffold and the basic workings for the search demo
> Search demo scaffold

- src/db/database.ts
- src/file/index-file.ts
> chore: revert #222

- src/file/multi.ts
- src/tests/bptree.test.ts
- src/tests/multipart.test.ts
Removed code rot.
This PR doesn't change any logic or include any new features. Feel free to disregard
> chore: make vars readonly, add await calls, remove unused code

- src/tests/multipart.test.ts
Sorry, I set auto-merge to true, but caught that a test failed
> Fix test, re:chore

- examples/search/index.html
- src/db/database.ts
- src/ngram/table.ts
- src/tests/ngramtable.test.ts
> feat: add ranking feature

- examples/search/index.html
This PR isn't significant, it contains a lot of demo-related work like js and CSS.
> feat: a working search

- src/btree/btree.ts
- src/btree/node.ts
- src/db/database.ts
- src/tests/btree.test.ts
We can generate a term frequency map for a given `BTree` and a `ReferenceValue`.
> feat: tfmap

- examples/search/index.html
- src/db/database.ts
Omit length normalization part in ranking heuristic. Demo work
> feat: change rank

- cmd/main.go
- pkg/appendable/index_file.go
- pkg/metapage/multi.go
Looks like this was still left in, bad merge maybe?
> chore: remove n offsets code

- cmd/main.go
- pkg/appendable/index_file.go
- pkg/metapage/multi.go
Reverts kevmo314/appendable#243
> Revert "chore: remove n offsets code"

- examples/search/index.html
Conditionally display a HTMLElement that provides context behind the demo. Also provided helpful keywords:
> feat: Search demo ux

- Cargo.toml
- examples/search/index.html
- scripts/jsonl2json/Cargo.toml
- scripts/jsonl2json/src/main.rs
Algolia doesn't support `.jsonl` so this quick script converts it into a `.json` file. It's a array of json objects
> feat: `jsonl2json` script

- pkg/metapage/multi.go
This PR is a follow up from #245 where we replace magic numbers for a more readable pattern
> remove magic numbers

- go.mod
https://go.dev/blog/go1.22
I find myself ranging over integers a lot :0
> chore: Update to 1.22

- pkg/appendable/appendable_test.go
- pkg/metapage/multi.go
Some test cases for `appendable.go` like creating a new tree, adding some pages, marshaling the metadata
> Marshal coverage

- pkg/metapage/multi.go
The hex editor shows we now store 8 bytes for `NextPointer`.
> feat: change next ptr to be of size 8

- src/file/multi.ts
> feat: remove buffer

- pkg/hnsw/hnsw.go
- pkg/hnsw/hnsw_test.go
- pkg/hnsw/node.go
- pkg/hnsw/vector.go
These are the primary resources I've been using so far:
- the paper [https://arxiv.org/pdf/1603.09320]
- facebook hnsw [https://www.pinecone.io/learn/series/faiss/hnsw/]
> feat: init vector search

- pkg/hnsw/eucqueue.go
- pkg/hnsw/eucqueue_test.go
- pkg/hnsw/hnsw.go
- pkg/hnsw/hnsw_test.go
- pkg/hnsw/node.go
> chore: Rename NodeID

- pkg/hnsw/hnsw.go
Given a queue of candidates and M, return M closest candidates
> feat: Select-Neighbors

- pkg/hnsw/eucqueue.go
- pkg/hnsw/hnsw.go
> feat: knn search

- pkg/hnsw/eucqueue.go
- pkg/hnsw/hnsw.go
Since all methods are drafted after `insert`, I'll start testing
> feat: insert

- pkg/hnsw/eucqueue.go
- pkg/hnsw/eucqueue_test.go
- pkg/hnsw/hnsw.go
- pkg/hnsw/hnsw_test.go
Tests that I wrote when I encountered a problem with priority queues and floats. Currently rewriting
> Earlier tests

- pkg/hnsw/eucqueue.go
- pkg/hnsw/eucqueue_test.go
- pkg/hnsw/hnsw.go
- pkg/hnsw/hnsw_test.go
- pkg/hnsw/node.go
The select neighbor algorithm can be condensed to the following.
> refactor select neighbor

- .github/workflows/example-client.yml
We need to index the description column
> Update client ci

- pkg/hnsw/hnsw.go
- pkg/hnsw/hnsw_test.go
- pkg/hnsw/node.go
Verify adding bidirectional links between nodes works correctly
> update node logic

- pkg/hnsw/hnsw.go
- pkg/hnsw/hnsw_test.go
- pkg/hnsw/node.go
- pkg/hnsw/node_test.go
When creating a new node, this PR not only allocates the friends array but also generates N number of elements where N = # of layers.
> feat: fix friends

- pkg/hnsw/hnsw_test.go
Given a cluster C, step through and make sure friends are being made.
> cluster assert

- .github/workflows/example-client.yml
- examples/client/index.html
- src/btree/btree.ts
> feat: cache root node + memptr

- pkg/hnsw/pq.go
- pkg/hnsw/pq_test.go
We need a way to interchange between priority queues based on their comparators (min or max).
> feat: from base queue

- pkg/hnsw/hnsw_test.go
https://www.desmos.com/calculator/yeoiw1hqkv
Given this cluster, and an entry point of (0, 0). We want to `searchLayer` with the target point being (0.5, 0.5). Note this point exists in the cluster, and upon searching, it should select that as the new entry point
> search layer given a cluster

- pkg/hnsw/hnsw_test.go
https://www.desmos.com/calculator/jme6fu7amq
Cluster C is the combination of cluster a and b. 
We seek to find the closest neighbor, and then find the top 4 nearest neighbors.
> SearchLayer given Clusters A, B

- pkg/hnsw/friends.go
- pkg/hnsw/hnsw_test.go
Will find the closest point that resides any layer above the `q`'s `topLayer`.
> Assert `findClosestPoint`

- pkg/hnsw/hnsw.go
- pkg/hnsw/hnsw_test.go
> feat: select neighbor

- pkg/hnsw/hnsw_test.go
Given this following cluster, we seek to find the three closest elements where `q` is `(0.27, 0.23)`.
> search in cluster a
